//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStackToolkit.Automation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceStackToolkit.Automation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request field &apos;{0}&apos; is specified in the route of its verb, but is not of the correct data type. You must set the data type property to &apos;{1}&apos;..
        /// </summary>
        internal static string RoutedRequestFieldDataTypeValidator_DataTypeInvalid {
            get {
                return ResourceManager.GetString("RoutedRequestFieldDataTypeValidator_DataTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verb &apos;{0}&apos; requires at least one field of the request contract of type &apos;{2}&apos;, called &apos;{1}&apos;. You must add a new field to the Request Contract called &apos;{1}&apos; with data type &apos;{2}&apos;.
        /// </summary>
        internal static string VerbIdRequestFieldValidator_IdRequestFieldMissing {
            get {
                return ResourceManager.GetString("VerbIdRequestFieldValidator_IdRequestFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property for the &apos;{1}&apos; verb with value of: &apos;{2}&apos; is not valid. Routes must start with a &apos;/&apos; and include the names of resources or fields (case-sensitive) separated by &apos;/&apos;.  They may also include substitutions for specific request fields (in squiggly braces &apos;{{&apos; and &apos;}}&apos;). i.e. /resource1/{{Id1}}/resource2/{{Id2}}/resource3.
        /// </summary>
        internal static string VerbRouteValidator_InvalidFormat {
            get {
                return ResourceManager.GetString("VerbRouteValidator_InvalidFormat", resourceCulture);
            }
        }
    }
}
