//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStackToolkit
{
	using global::NuPattern.Runtime;
	using global::NuPattern.Runtime.Bindings;
	using global::NuPattern.Runtime.ToolkitInterface;
	using global::System;
	using global::System.Collections.Generic;
	using global::System.ComponentModel;
	using global::System.ComponentModel.Design;
	using global::System.Drawing.Design;
	using Runtime = global::NuPattern.Runtime;

	/// <summary>
	/// The REST web services in the project
	/// </summary>
	[Description("The REST web services in the project")]
	[ToolkitInterface(ExtensionId = "B4A8F72C-332B-4154-9351-F7049C24567D", DefinitionId = "55c285d6-8bac-45a8-85dd-605beed51a26", ProxyType = typeof(Services))]
	[System.CodeDom.Compiler.GeneratedCode("NuPattern Toolkit Library", "1.4.24.0")]
	public partial interface IServices : IToolkitInterface
	{

		/// <summary>
		/// The name of this element instance.
		/// </summary>
		[Description("The name of this element instance.")]
		[ParenthesizePropertyName(true)]
		String InstanceName { get; set; }

		/// <summary>
		/// The order of this element relative to its siblings.
		/// </summary>
		[Description("The order of this element relative to its siblings.")]
		[ReadOnly(true)]
		Double InstanceOrder { get; set; }

		/// <summary>
		/// The references of this element.
		/// </summary>
		[Description("The references of this element.")]
		IEnumerable<IReference> References { get; }

		/// <summary>
		/// Notes for this element.
		/// </summary>
		[Description("Notes for this element.")]
		[Editor(typeof(MultilineStringEditor), typeof(UITypeEditor))]
		String Notes { get; set; }

		/// <summary>
		/// Gets or sets the InTransaction property.
		/// </summary>
		Boolean InTransaction { get; }

		/// <summary>
		/// Gets or sets the IsSerializing property.
		/// </summary>
		Boolean IsSerializing { get; }

		/// <summary>
		/// Gets the parent element.
		/// </summary>
		IWebServices Parent { get; }

		/// <summary>
		/// Gets all instances of <see cref="IService"/> contained in this element.
		/// </summary>
		IEnumerable<IService> Service { get; }

		/// <summary>
		/// Creates a new <see cref="IService"/>  and adds it to the <see cref="Service"/> collection,  
		/// executing the optional <paramref name="initializer"/> if not <see langword="null"/>.
		/// </summary>
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed")]
		IService CreateService(string name, Action<IService> initializer = null, bool raiseInstantiateEvents = true);

		/// <summary>
		/// Deletes this element.
		/// </summary>
		void Delete();

		/// <summary>
		/// Gets the generalized interface (<see cref="Runtime.ICollection"/>) of this element.
		/// </summary>
		Runtime.ICollection AsCollection();
	}
}

namespace ServiceStackToolkit
{
	using global::NuPattern.Runtime;
	using global::NuPattern.Runtime.Bindings;
	using global::NuPattern.Runtime.ToolkitInterface;
	using global::System;
	using global::System.Collections.Generic;
	using global::System.ComponentModel;
	using global::System.ComponentModel.Design;
	using global::System.Drawing.Design;
	using Runtime = global::NuPattern.Runtime;

	/// <summary>
	/// Tests for the web service
	/// </summary>
	[Description("Tests for the web service")]
	[ToolkitInterface(ExtensionId = "B4A8F72C-332B-4154-9351-F7049C24567D", DefinitionId = "e0f60dd5-2d78-4c16-9780-e134ce626484", ProxyType = typeof(Tests))]
	[System.CodeDom.Compiler.GeneratedCode("NuPattern Toolkit Library", "1.4.24.0")]
	public partial interface ITests : IToolkitInterface
	{

		/// <summary>
		/// The name of this element instance.
		/// </summary>
		[Description("The name of this element instance.")]
		[ParenthesizePropertyName(true)]
		String InstanceName { get; set; }

		/// <summary>
		/// The order of this element relative to its siblings.
		/// </summary>
		[Description("The order of this element relative to its siblings.")]
		[ReadOnly(true)]
		Double InstanceOrder { get; set; }

		/// <summary>
		/// The references of this element.
		/// </summary>
		[Description("The references of this element.")]
		IEnumerable<IReference> References { get; }

		/// <summary>
		/// Notes for this element.
		/// </summary>
		[Description("Notes for this element.")]
		[Editor(typeof(MultilineStringEditor), typeof(UITypeEditor))]
		String Notes { get; set; }

		/// <summary>
		/// Gets or sets the InTransaction property.
		/// </summary>
		Boolean InTransaction { get; }

		/// <summary>
		/// Gets or sets the IsSerializing property.
		/// </summary>
		Boolean IsSerializing { get; }

		/// <summary>
		/// Gets the parent element.
		/// </summary>
		IWebServices Parent { get; }

		/// <summary>
		/// Gets the <see cref="IUnitTests"/> contained in this element.
		/// </summary>
		IUnitTests UnitTests { get; }

		/// <summary>
		/// Gets the <see cref="IIntegrationTests"/> contained in this element.
		/// </summary>
		IIntegrationTests IntegrationTests { get; }

		/// <summary>
		/// Creates a new <see cref="IUnitTests"/>  
		/// executing the optional <paramref name="initializer"/> if not <see langword="null"/>.
		/// </summary>
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed")]
		IUnitTests CreateUnitTests(string name, Action<IUnitTests> initializer = null, bool raiseInstantiateEvents = true);

		/// <summary>
		/// Creates a new <see cref="IIntegrationTests"/>  
		/// executing the optional <paramref name="initializer"/> if not <see langword="null"/>.
		/// </summary>
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed")]
		IIntegrationTests CreateIntegrationTests(string name, Action<IIntegrationTests> initializer = null, bool raiseInstantiateEvents = true);

		/// <summary>
		/// Deletes this element.
		/// </summary>
		void Delete();

		/// <summary>
		/// Gets the generalized interface (<see cref="Runtime.ICollection"/>) of this element.
		/// </summary>
		Runtime.ICollection AsCollection();
	}
}
