//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStackToolkit
{
	using global::NuPattern.Runtime;
	using global::NuPattern.Runtime.ToolkitInterface;
	using global::System;
	using global::System.Collections.Generic;
	using global::System.ComponentModel;
	using global::System.ComponentModel.Composition;
	using global::System.ComponentModel.Design;
	using global::System.Drawing.Design;
	using Runtime = global::NuPattern.Runtime;

	/// <summary>
	/// Description for Solution.DefaultView
	/// </summary>
	[Description("Description for Solution.DefaultView")]
	[ToolkitInterfaceProxy(ExtensionId = "B4A8F72C-332B-4154-9351-F7049C24567D", DefinitionId = "8fc008cc-cafc-4e4c-92f3-f77f636efdc3", ProxyType = typeof(DefaultView))]
	[System.CodeDom.Compiler.GeneratedCode("NuPattern Toolkit Library", "1.4.24.0")]
	[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	internal partial class DefaultView : IDefaultView
	{

		private Runtime.IView target;
		private IContainerProxy<IDefaultView> proxy;

		/// <summary>
		/// Creates a new instance of the <see cref="DefaultView"/> class.
		/// </summary>
		[ImportingConstructor]
		private DefaultView() { }

		/// <summary>
		/// Creates a new instance of the <see cref="DefaultView"/> class.
		/// </summary>
		public DefaultView(Runtime.IView target)
		{
			this.target = target;
			this.proxy = target.ProxyFor<IDefaultView>();
			OnCreated();
		}

		/// <summary>
		/// When overridden, initializes the class.
		/// </summary>
		partial void OnCreated();

		/// <summary>
		/// Gets the parent element.
		/// </summary>
		public virtual ISolution Parent
		{
			get { return this.target.Parent.As<ISolution>(); }
		}

		/// <summary>
		/// Gets the <see cref="IWebServices"/> contained in this element.
		/// </summary>
		public virtual IWebServices WebServices
		{
			get { return proxy.GetElement(() => this.WebServices, element => new WebServices(element)); }
		}

		/// <summary>
		/// Creates a new <see cref="IWebServices"/>  
		/// executing the optional <paramref name="initializer"/> if not <see langword="null"/>.
		/// </summary>
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed")]
		public virtual IWebServices CreateWebServices(string name, Action<IWebServices> initializer = null, bool raiseInstantiateEvents = true)
		{
			return proxy.CreateElement<IWebServices>(name, initializer, raiseInstantiateEvents);
		}

		/// <summary>
		/// Deletes this element.
		/// </summary>
		public virtual void Delete()
		{
			this.target.Delete();
		}

		/// <summary>
		/// Gets the generalized interface (<see cref="Runtime.IView"/>) of this element.
		/// </summary>
		public virtual Runtime.IView AsView()
		{
			return this.target;
		}

		/// <summary>
		/// Gets the specified generalized interface of this element, if possible.
		/// </summary>
		public virtual TGeneralizedInterface As<TGeneralizedInterface>() where TGeneralizedInterface : class
		{
			return this.target as TGeneralizedInterface;
		}
	}
}
